#!/bin/sh
### BEGIN INIT INFO
# Provides:          slonklet-controller
# Required-Start:    $remote_fs $syslog munge
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Slurm REST API daemon
### END INIT INFO

. /lib/lsb/init-functions

PIDFILE=/var/run/slonklet-controller.pid
SLONKLET_CONTROLLER_OPTIONS=$(grep SLONKLET_CONTROLLER_OPTIONS /etc/sysconfig/slonklet-controller | cut -d'=' -f2-)

start() {
    log_daemon_msg "Starting slonklet-controller" "slonklet-controller"
    if [ -f /home/common/slonklet-controller/slonklet-controller ] && [ -f /etc/sysconfig/slonklet-controller ]; then
        export KUBERNETES_SERVICE_HOST=kubernetes.default.svc
        export KUBERNETES_SERVICE_PORT=443
        eval start-stop-daemon --start --background --quiet --output /var/log/slurm/slonklet-controller.out --make-pidfile --pidfile $PIDFILE --exec /home/common/slonklet-controller/slonklet-controller -- $SLONKLET_CONTROLLER_OPTIONS
        log_end_msg $?
    else
        log_failure_msg "failed to start slonklet-controller"
    fi
}

stop() {
    log_daemon_msg "Stopping slonklet-controller" "slonklet-controller"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry TERM/5/KILL/2
    log_end_msg $?
}

status() {
    if [ -f $PIDFILE ]; then
        pid=$(cat $PIDFILE)
        if kill -0 $pid > /dev/null 2>&1; then
            echo "slonklet-controller is running with pid $pid"
        else
            echo "slonklet-controller is not running"
        fi
    else
        echo "slonklet-controller is not running"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: /etc/init.d/slonklet-controller {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
