#!/bin/sh
### BEGIN INIT INFO
# Provides:          slurmd
# Required-Start:    $remote_fs $syslog munge
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Slurm controller daemon
### END INIT INFO

. /lib/lsb/init-functions

PIDFILE=/var/run/slurmd.pid
SLURMD_OPTIONS=$(grep SLURMD_OPTIONS /etc/sysconfig/slurmd | cut -d'=' -f2-)

start() {
    log_daemon_msg "Starting slurm controller daemon" "slurmd"
    if [ -f /etc/slurm/slurm.conf ]; then
        eval start-stop-daemon --start --quiet --pidfile $PIDFILE --exec /usr/sbin/slurmd -- $SLURMD_OPTIONS
        log_end_msg $?
    else
        log_failure_msg "/etc/slurm/slurm.conf not found"
    fi
}

stop() {
    log_daemon_msg "Stopping slurm controller daemon" "slurmd"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry TERM/30/KILL/5
    log_end_msg $?
}

status() {
    if [ -f $PIDFILE ]; then
        pid=$(cat $PIDFILE)
        if kill -0 $pid > /dev/null 2>&1; then
            echo "slurmd is running with pid $pid"
        else
            echo "slurmd is not running"
        fi
    else
        echo "slurmd is not running"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: /etc/init.d/slurmd {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
