//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventRecord) DeepCopyInto(out *EventRecord) {
	*out = *in
	in.Event.DeepCopyInto(&out.Event)
	in.AckTimestamp.DeepCopyInto(&out.AckTimestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventRecord.
func (in *EventRecord) DeepCopy() *EventRecord {
	if in == nil {
		return nil
	}
	out := new(EventRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sNodeSpec) DeepCopyInto(out *K8sNodeSpec) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sNodeSpec.
func (in *K8sNodeSpec) DeepCopy() *K8sNodeSpec {
	if in == nil {
		return nil
	}
	out := new(K8sNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sNodeStatus) DeepCopyInto(out *K8sNodeStatus) {
	*out = *in
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]corev1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sNodeStatus.
func (in *K8sNodeStatus) DeepCopy() *K8sNodeStatus {
	if in == nil {
		return nil
	}
	out := new(K8sNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalNode) DeepCopyInto(out *PhysicalNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	if in.EventRecords != nil {
		in, out := &in.EventRecords, &out.EventRecords
		*out = make([]EventRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalNode.
func (in *PhysicalNode) DeepCopy() *PhysicalNode {
	if in == nil {
		return nil
	}
	out := new(PhysicalNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PhysicalNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalNodeList) DeepCopyInto(out *PhysicalNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PhysicalNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalNodeList.
func (in *PhysicalNodeList) DeepCopy() *PhysicalNodeList {
	if in == nil {
		return nil
	}
	out := new(PhysicalNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PhysicalNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalNodeSnapshot) DeepCopyInto(out *PhysicalNodeSnapshot) {
	*out = *in
	out.AccumulatedRuntime = in.AccumulatedRuntime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalNodeSnapshot.
func (in *PhysicalNodeSnapshot) DeepCopy() *PhysicalNodeSnapshot {
	if in == nil {
		return nil
	}
	out := new(PhysicalNodeSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalNodeSpec) DeepCopyInto(out *PhysicalNodeSpec) {
	*out = *in
	in.SlurmNodeSpec.DeepCopyInto(&out.SlurmNodeSpec)
	in.K8sNodeSpec.DeepCopyInto(&out.K8sNodeSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalNodeSpec.
func (in *PhysicalNodeSpec) DeepCopy() *PhysicalNodeSpec {
	if in == nil {
		return nil
	}
	out := new(PhysicalNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalNodeStatus) DeepCopyInto(out *PhysicalNodeStatus) {
	*out = *in
	in.SlurmNodeStatus.DeepCopyInto(&out.SlurmNodeStatus)
	if in.SlurmNodeStatusHistory != nil {
		in, out := &in.SlurmNodeStatusHistory, &out.SlurmNodeStatusHistory
		*out = make([]SlurmNodeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.K8sNodeStatus.DeepCopyInto(&out.K8sNodeStatus)
	if in.K8sNodeStatusHistory != nil {
		in, out := &in.K8sNodeStatusHistory, &out.K8sNodeStatusHistory
		*out = make([]K8sNodeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalNodeStatus.
func (in *PhysicalNodeStatus) DeepCopy() *PhysicalNodeStatus {
	if in == nil {
		return nil
	}
	out := new(PhysicalNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlurmJob) DeepCopyInto(out *SlurmJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlurmJob.
func (in *SlurmJob) DeepCopy() *SlurmJob {
	if in == nil {
		return nil
	}
	out := new(SlurmJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlurmJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlurmJobList) DeepCopyInto(out *SlurmJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlurmJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlurmJobList.
func (in *SlurmJobList) DeepCopy() *SlurmJobList {
	if in == nil {
		return nil
	}
	out := new(SlurmJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlurmJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlurmJobRunStatus) DeepCopyInto(out *SlurmJobRunStatus) {
	*out = *in
	if in.PhysicalNodeSnapshots != nil {
		in, out := &in.PhysicalNodeSnapshots, &out.PhysicalNodeSnapshots
		*out = make(map[string]*PhysicalNodeSnapshot, len(*in))
		for key, val := range *in {
			var outVal *PhysicalNodeSnapshot
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(PhysicalNodeSnapshot)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	in.SubmitTimestamp.DeepCopyInto(&out.SubmitTimestamp)
	in.StartTimestamp.DeepCopyInto(&out.StartTimestamp)
	in.LastSyncTimestamp.DeepCopyInto(&out.LastSyncTimestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlurmJobRunStatus.
func (in *SlurmJobRunStatus) DeepCopy() *SlurmJobRunStatus {
	if in == nil {
		return nil
	}
	out := new(SlurmJobRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlurmJobSpec) DeepCopyInto(out *SlurmJobSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlurmJobSpec.
func (in *SlurmJobSpec) DeepCopy() *SlurmJobSpec {
	if in == nil {
		return nil
	}
	out := new(SlurmJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlurmJobStatus) DeepCopyInto(out *SlurmJobStatus) {
	*out = *in
	in.SlurmJobRunCurrentStatus.DeepCopyInto(&out.SlurmJobRunCurrentStatus)
	if in.SlurmJobRunStatusHistory != nil {
		in, out := &in.SlurmJobRunStatusHistory, &out.SlurmJobRunStatusHistory
		*out = make([]SlurmJobRunStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlurmJobStatus.
func (in *SlurmJobStatus) DeepCopy() *SlurmJobStatus {
	if in == nil {
		return nil
	}
	out := new(SlurmJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlurmNodeSpec) DeepCopyInto(out *SlurmNodeSpec) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlurmNodeSpec.
func (in *SlurmNodeSpec) DeepCopy() *SlurmNodeSpec {
	if in == nil {
		return nil
	}
	out := new(SlurmNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlurmNodeStatus) DeepCopyInto(out *SlurmNodeStatus) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlurmNodeStatus.
func (in *SlurmNodeStatus) DeepCopy() *SlurmNodeStatus {
	if in == nil {
		return nil
	}
	out := new(SlurmNodeStatus)
	in.DeepCopyInto(out)
	return out
}
